import { Request, Response } from 'express';
import DietPlan from '../models/DietPlan';

export const getDietPlan = async (req: any, res: Response) => {
    try {
        const diet = await DietPlan.findOne({ userId: req.user.id }).sort({ createdAt: -1 });
        if (!diet) {
            return res.status(200).json({
                calories: 2200,
                protein: 150,
                carbs: 250,
                fats: 70,
                meals: [
                    { name: 'Oatmeal with Blueberries', description: 'High fiber breakfast', calories: 350, protein: 10 },
                    { name: 'Grilled Chicken Salad', description: 'Protein rich lunch', calories: 450, protein: 40 },
                    { name: 'Salmon and Quinoa', description: 'Healthy fats dinner', calories: 600, protein: 35 }
                ]
            });
        }
        
        // Map to requested format
        res.status(200).json({
            calories: diet.dailyCalories,
            protein: diet.protein,
            carbs: diet.carbs,
            fats: diet.fats,
            meals: diet.meals || []
        });
    } catch (error) {
        res.status(500).json({ message: 'Server error' });
    }
};

export const generateDietPlan = async (req: any, res: Response) => {
    try {
        // AI Logic would go here. For now, mock a generation.
        const newDiet = new DietPlan({
            userId: req.user.id,
            dailyCalories: Math.floor(Math.random() * 500) + 1800,
            protein: 160,
            carbs: 200,
            fats: 60,
            meals: [
                { name: 'AI Generated Meal 1', description: 'Generated by AstraFit AI', calories: 500, protein: 30 }
            ]
        });
        await newDiet.save();
        res.status(201).json(newDiet);
    } catch (error) {
        res.status(500).json({ message: 'Server error' });
    }
};

export const updateDietPreferences = async (req: any, res: Response) => {
    try {
        const { dietType, intermittentFasting } = req.body;
        // In real app, update user prefs or a specific config
        res.status(200).json({ message: 'Preferences updated' });
    } catch (error) {
        res.status(500).json({ message: 'Server error' });
    }
};
