import { Request, Response } from 'express';
import DietPlan from '../models/DietPlan';

export const getDietPlan = async (req: any, res: Response) => {
    try {
        const diet = await DietPlan.findOne({ userId: req.user.id }).sort({ createdAt: -1 });
        if (!diet) {
            return res.status(200).json({
                dailyCalories: 1850,
                protein: 160,
                carbs: 210,
                fats: 55,
                meals: [
                    { name: 'Overnight Berry Oats', description: 'Oats, Blueberries, Almond Milk', calories: 420, protein: 12 },
                    { name: 'Grilled Chicken Quinoa Bowl', description: 'Chicken Breast, Quinoa, Avocado', calories: 580, protein: 45 }
                ],
                supplements: ['Multivitanim', 'Whey Isolate']
            });
        }
        res.status(200).json(diet);
    } catch (error) {
        res.status(500).json({ message: 'Server error' });
    }
};

export const generateDietPlan = async (req: any, res: Response) => {
    try {
        // AI Logic would go here. For now, mock a generation.
        const newDiet = new DietPlan({
            userId: req.user.id,
            dailyCalories: Math.floor(Math.random() * 500) + 1800,
            protein: 160,
            carbs: 200,
            fats: 60,
            meals: [
                { name: 'AI Generated Meal 1', description: 'Generated by OnlyFitness AI', calories: 500, protein: 30 }
            ]
        });
        await newDiet.save();
        res.status(201).json(newDiet);
    } catch (error) {
        res.status(500).json({ message: 'Server error' });
    }
};

export const updateDietPreferences = async (req: any, res: Response) => {
    try {
        const { dietType, intermittentFasting } = req.body;
        // In real app, update user prefs or a specific config
        res.status(200).json({ message: 'Preferences updated' });
    } catch (error) {
        res.status(500).json({ message: 'Server error' });
    }
};
